import mongoose from 'mongoose';

const reportSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    summary: {
      type: String,
      required: true,
    },
    transactionSummary: {
      totalIn: { type: Number, default: 0 },
      totalOut: { type: Number, default: 0 },
      totalTransactions: { type: Number, default: 0 },
      netBalance: { type: Number, default: 0 },
    },
    riskSummary: {
      normalCount: { type: Number, default: 0 },
      lowRiskCount: { type: Number, default: 0 },
      mediumRiskCount: { type: Number, default: 0 },
      highRiskCount: { type: Number, default: 0 },
      needsReviewCount: { type: Number, default: 0 },
    },
    flaggedTransactions: [
      {
        transactionId: String,
        date: Date,
        amount: Number,
        type: String,
        sender: String,
        receiver: String,
        riskScore: Number,
        riskLevel: String,
        indicators: [String],
        reason: String,
      },
    ],
    flowSummary: {
      type: String,
      default: '',
    },
    aiExplanations: [
      {
        title: String,
        content: String,
      },
    ],
    disclaimer: {
      type: String,
      default: 'This report indicates risk patterns only and does not establish that funds are illegal or constitute black money. Generated by MoneyTrace AI.',
    },
  },
  {
    timestamps: true,
  }
);

reportSchema.index({ userId: 1, createdAt: -1 });

export const Report = mongoose.model('Report', reportSchema);
