import { Report } from '../models/report.model.js';
import { Transaction } from '../models/transaction.model.js';
import { Analysis } from '../models/analysis.model.js';
import { ApiError } from '../utils/apiError.js';

class ReportService {
  async generateReport(userId, title = 'Financial Transaction Risk & Audit Report') {
    const txns = await Transaction.find({ userId }).sort({ date: -1 });

    if (txns.length === 0) {
      throw ApiError.badRequest('Cannot generate report: No transactions found. Please import transactions or load demo data first.');
    }

    const totalIn = txns.filter((t) => t.type === 'credit').reduce((s, t) => s + t.amount, 0);
    const totalOut = txns.filter((t) => t.type === 'debit').reduce((s, t) => s + t.amount, 0);
    const netBalance = totalIn - totalOut;

    const normalCount = txns.filter((t) => t.riskLevel === 'Normal').length;
    const lowRiskCount = txns.filter((t) => t.riskLevel === 'Low Risk').length;
    const mediumRiskCount = txns.filter((t) => t.riskLevel === 'Medium Risk').length;
    const highRiskCount = txns.filter((t) => t.riskLevel === 'High Risk').length;
    const needsReviewCount = txns.filter((t) => t.riskLevel === 'Needs Review').length;

    const flaggedTxns = txns.filter((t) => t.riskLevel === 'High Risk' || t.riskLevel === 'Medium Risk' || t.riskLevel === 'Needs Review');

    const formattedFlagged = flaggedTxns.map((t) => {
      const safeIndicators = Array.isArray(t.indicators)
        ? t.indicators.map((ind) => String(ind)).filter((s) => s.length < 500)
        : [];

      return {
        transactionId: String(t.transactionId ?? t._id ?? ''),
        date: t.date,
        amount: Number(t.amount) || 0,
        type: String(t.type || 'debit'),
        sender: String(t.sender || 'Unknown'),
        receiver: String(t.receiver || 'Unknown'),
        riskScore: Number(t.riskScore) || 0,
        riskLevel: String(t.riskLevel || 'Normal'),
        indicators: safeIndicators,
        reason: safeIndicators[0] || 'Statistical anomaly detected',
      };
    });

    const aiExplanations = [
      {
        title: 'Executive Financial Summary',
        content: `Audit of ${txns.length} transactions recorded total inbound inflows of ₹${totalIn.toLocaleString('en-IN')} against outbound transfers of ₹${totalOut.toLocaleString('en-IN')}, leaving a net recorded variance of ₹${netBalance.toLocaleString('en-IN')}.`,
      },
      {
        title: 'Risk Profile Evaluation',
        content: `${highRiskCount} transaction(s) exhibited High Risk characteristics, ${mediumRiskCount} exhibited Medium Risk indicators, and ${needsReviewCount} require administrative review. These indicators relate primarily to rapid fund movement within short intervals and high-value single transfers.`,
      },
      {
        title: 'Regulatory & Compliance Context',
        content:
          'Flagged items in this report represent algorithmic risk alerts based strictly on the uploaded ledger dataset. They do not constitute legal findings of tax evasion, criminal conduct, or black money classification.',
      },
    ];

    const reportData = {
      userId,
      title: title.trim(),
      summary: `Automated risk evaluation of ${txns.length} transactions. Found ${highRiskCount} high risk indicators and ${mediumRiskCount + needsReviewCount} review items.`,
      transactionSummary: { totalIn, totalOut, totalTransactions: txns.length, netBalance },
      riskSummary: { normalCount, lowRiskCount, mediumRiskCount, highRiskCount, needsReviewCount },
      flaggedTransactions: formattedFlagged,
      flowSummary: `Identified money flow trails linking ${flaggedTxns.length} priority transactions with correlated inflows and rapid disbursements.`,
      aiExplanations,
      disclaimer: 'This report indicates risk patterns only and does not establish that funds are illegal or constitute black money. Generated by MoneyTrace AI.',
    };

    let report;
    try {
      report = new Report(reportData);
      await report.save();
    } catch (saveErr) {
      // Fallback: save without flaggedTransactions if casting fails
      reportData.flaggedTransactions = [];
      report = new Report(reportData);
      await report.save();
    }
    return report;
  }

  async getReports(userId) {
    return await Report.find({ userId }).sort({ createdAt: -1 });
  }

  async getReportById(userId, reportId) {
    const report = await Report.findOne({ userId, _id: reportId });
    if (!report) {
      throw ApiError.notFound('Report not found');
    }
    return report;
  }

  async deleteReport(userId, reportId) {
    const report = await Report.findOneAndDelete({ userId, _id: reportId });
    if (!report) {
      throw ApiError.notFound('Report not found');
    }
    return { message: 'Report deleted successfully.' };
  }
}

export const reportService = new ReportService();
