export const getDemoTransactions = (userId) => {
  const now = new Date();
  const daysAgo = (d, h = 10, m = 0) => {
    const dt = new Date(now);
    dt.setDate(dt.getDate() - d);
    dt.setHours(h, m, 0, 0);
    return dt;
  };

  return [
    // 1. Regular Monthly Salary (Normal)
    {
      userId,
      transactionId: 'TXN1001',
      date: daysAgo(28, 9, 30),
      description: 'Monthly Salary Credit - TechCorp Solutions',
      amount: 145000,
      type: 'credit',
      credit: 145000,
      debit: 0,
      balance: 185000,
      paymentMode: 'NEFT',
      sender: 'TechCorp Solutions Pvt Ltd',
      receiver: 'Self / Account Holder',
      referenceNumber: 'NEFT/N1001092834',
      riskScore: 5,
      riskLevel: 'Normal',
      indicators: ['Regular periodic income', 'Verified corporate originator'],
      isFlagged: false,
      source: 'demo',
    },
    // 2. Regular Utility payment (Normal)
    {
      userId,
      transactionId: 'TXN1002',
      date: daysAgo(26, 14, 15),
      description: 'Electricity Bill Payment - BESCOM',
      amount: 3200,
      type: 'debit',
      credit: 0,
      debit: 3200,
      balance: 181800,
      paymentMode: 'UPI',
      sender: 'Self / Account Holder',
      receiver: 'BESCOM Utilities',
      referenceNumber: 'UPI/2614150912',
      riskScore: 4,
      riskLevel: 'Normal',
      indicators: ['Routine utility expense'],
      isFlagged: false,
      source: 'demo',
    },
    // 3. Normal Grocery Supermarket (Normal)
    {
      userId,
      transactionId: 'TXN1003',
      date: daysAgo(24, 19, 45),
      description: 'Nature Fresh Supermarket Grocery Purchase',
      amount: 4850,
      type: 'debit',
      credit: 0,
      debit: 4850,
      balance: 176950,
      paymentMode: 'CARD',
      sender: 'Self / Account Holder',
      receiver: 'Nature Fresh Mart POS',
      referenceNumber: 'POS/98234710',
      riskScore: 3,
      riskLevel: 'Normal',
      indicators: ['Standard merchant POS purchase'],
      isFlagged: false,
      source: 'demo',
    },
    // 4. Moderate Friend Transfer (Low Risk)
    {
      userId,
      transactionId: 'TXN1004',
      date: daysAgo(20, 11, 20),
      description: 'Trip reimbursement from Rahul',
      amount: 12000,
      type: 'credit',
      credit: 12000,
      debit: 0,
      balance: 188950,
      paymentMode: 'UPI',
      sender: 'Rahul Verma (UPI: rahul@okhdfc)',
      receiver: 'Self / Account Holder',
      referenceNumber: 'UPI/2011204921',
      riskScore: 18,
      riskLevel: 'Low Risk',
      indicators: ['P2P credit transfer', 'Proportionate to typical balance'],
      isFlagged: false,
      source: 'demo',
    },
    // 5. Investment in Mutual Fund (Normal)
    {
      userId,
      transactionId: 'TXN1005',
      date: daysAgo(18, 10, 0),
      description: 'SIP Auto-Debit - Zerodha Fund House',
      amount: 25000,
      type: 'debit',
      credit: 0,
      debit: 25000,
      balance: 163950,
      paymentMode: 'ACH',
      sender: 'Self / Account Holder',
      receiver: 'Zerodha Broking Limited',
      referenceNumber: 'ACH/1810008432',
      riskScore: 6,
      riskLevel: 'Normal',
      indicators: ['Scheduled regulated investment debit'],
      isFlagged: false,
      source: 'demo',
    },
    // 6. Suspicious Cluster 1 - High Value Inbound (High Risk)
    // Inbound: ₹2,80,000 from Apex Trading
    {
      userId,
      transactionId: 'TXN1020',
      date: daysAgo(12, 10, 15),
      description: 'Urgent Consulting Advance Transfer',
      amount: 280000,
      type: 'credit',
      credit: 280000,
      debit: 0,
      balance: 443950,
      paymentMode: 'RTGS',
      sender: 'Apex Global Enterprises LLP',
      receiver: 'Self / Account Holder',
      referenceNumber: 'RTGS/R1210158902',
      riskScore: 82,
      riskLevel: 'High Risk',
      indicators: [
        'Unusually large amount relative to historic average',
        'Preceded subsequent rapid fund dissipation within 2 hours',
        'High value single transfer anomaly',
      ],
      isFlagged: true,
      source: 'demo',
    },
    // 7. Suspicious Cluster 1 - Rapid Outbound Pass-Through 1 (High Risk)
    // 40 mins later: -₹1,20,000 to Orbit Ventures
    {
      userId,
      transactionId: 'TXN1021',
      date: daysAgo(12, 10, 55),
      description: 'Equipment procurement distribution',
      amount: 120000,
      type: 'debit',
      credit: 0,
      debit: 120000,
      balance: 323950,
      paymentMode: 'IMPS',
      sender: 'Self / Account Holder',
      receiver: 'Orbit Tech Ventures Pvt Ltd',
      referenceNumber: 'IMPS/1210557431',
      riskScore: 88,
      riskLevel: 'High Risk',
      indicators: [
        'Rapid fund movement (dispatched 40 mins after large credit)',
        'Pass-through velocity indicator',
        'Multiple linked distribution hops',
      ],
      isFlagged: true,
      source: 'demo',
    },
    // 8. Suspicious Cluster 1 - Rapid Outbound Pass-Through 2 (High Risk)
    // 1 hr 15 mins later: -₹1,30,000 to Horizon Consultants
    {
      userId,
      transactionId: 'TXN1022',
      date: daysAgo(12, 11, 30),
      description: 'Subcontractor settlement part 2',
      amount: 130000,
      type: 'debit',
      credit: 0,
      debit: 130000,
      balance: 193950,
      paymentMode: 'IMPS',
      sender: 'Self / Account Holder',
      receiver: 'Horizon Advisory Services',
      referenceNumber: 'IMPS/1211309812',
      riskScore: 89,
      riskLevel: 'High Risk',
      indicators: [
        'Rapid movement of funds within 75 minutes of incoming ₹2,80,000',
        '89% of incoming funds liquidated across two parties rapidly',
        'Pass-through / conduit velocity pattern',
      ],
      isFlagged: true,
      source: 'demo',
    },
    // 9. Structuring / Smurfing Anomaly - Split Transfers 1 (Medium Risk)
    {
      userId,
      transactionId: 'TXN1030',
      date: daysAgo(7, 14, 10),
      description: 'Consulting milestone tranches A',
      amount: 49500,
      type: 'credit',
      credit: 49500,
      debit: 0,
      balance: 243450,
      paymentMode: 'IMPS',
      sender: 'Silverline Media Works',
      receiver: 'Self / Account Holder',
      referenceNumber: 'IMPS/0714108392',
      riskScore: 68,
      riskLevel: 'Medium Risk',
      indicators: [
        'Just below ₹50,000 statutory reporting threshold',
        'Part of rapid successive tranche transfers within 30 minutes',
      ],
      isFlagged: true,
      source: 'demo',
    },
    // 10. Structuring / Smurfing Anomaly - Split Transfers 2 (Medium Risk)
    {
      userId,
      transactionId: 'TXN1031',
      date: daysAgo(7, 14, 25),
      description: 'Consulting milestone tranches B',
      amount: 49500,
      type: 'credit',
      credit: 49500,
      debit: 0,
      balance: 292950,
      paymentMode: 'IMPS',
      sender: 'Silverline Media Works',
      receiver: 'Self / Account Holder',
      referenceNumber: 'IMPS/0714259834',
      riskScore: 71,
      riskLevel: 'Medium Risk',
      indicators: [
        'Identical split amount ₹49,500 within 15 minutes',
        'Frequent structuring indicator below ₹50,000 threshold',
      ],
      isFlagged: true,
      source: 'demo',
    },
    // 11. Rapid Forwarding (Needs Review)
    {
      userId,
      transactionId: 'TXN1032',
      date: daysAgo(7, 15, 5),
      description: 'Vendor payment payout to Zenith',
      amount: 85000,
      type: 'debit',
      credit: 0,
      debit: 85000,
      balance: 207950,
      paymentMode: 'NEFT',
      sender: 'Self / Account Holder',
      receiver: 'Zenith Logistics Hub',
      referenceNumber: 'NEFT/0715059910',
      riskScore: 62,
      riskLevel: 'Needs Review',
      indicators: [
        'Transfers shortly after split incoming credits',
        'Needs verification of commercial invoice',
      ],
      isFlagged: true,
      source: 'demo',
    },
    // 12. Normal Dining & Leisure
    {
      userId,
      transactionId: 'TXN1040',
      date: daysAgo(4, 20, 10),
      description: 'The Olive Bistro Family Dinner',
      amount: 3600,
      type: 'debit',
      credit: 0,
      debit: 3600,
      balance: 204350,
      paymentMode: 'UPI',
      sender: 'Self / Account Holder',
      receiver: 'Olive Bistro UPI',
      referenceNumber: 'UPI/0420108341',
      riskScore: 4,
      riskLevel: 'Normal',
      indicators: ['Normal dining transaction'],
      isFlagged: false,
      source: 'demo',
    },
    // 13. Unusual Late Night Cash Withdrawal (Needs Review)
    {
      userId,
      transactionId: 'TXN1045',
      date: daysAgo(2, 2, 45),
      description: 'ATM Cash Withdrawal HDFC ATM Branch 401',
      amount: 20000,
      type: 'debit',
      credit: 0,
      debit: 20000,
      balance: 184350,
      paymentMode: 'CASH',
      sender: 'Self / Account Holder',
      receiver: 'Self (ATM Dispenser)',
      referenceNumber: 'ATM/0202458923',
      riskScore: 55,
      riskLevel: 'Needs Review',
      indicators: [
        'Unusual transaction timing (02:45 AM)',
        'Cash withdrawal deviation from standard spending habits',
      ],
      isFlagged: true,
      source: 'demo',
    },
    // 14. Fresh Incoming Reimbursement (Low Risk)
    {
      userId,
      transactionId: 'TXN1050',
      date: daysAgo(1, 16, 20),
      description: 'Client travel advance return',
      amount: 18500,
      type: 'credit',
      credit: 18500,
      debit: 0,
      balance: 202850,
      paymentMode: 'UPI',
      sender: 'Kunal Deshmukh',
      receiver: 'Self / Account Holder',
      referenceNumber: 'UPI/0116209844',
      riskScore: 15,
      riskLevel: 'Low Risk',
      indicators: ['Routine peer credit'],
      isFlagged: false,
      source: 'demo',
    },
  ];
};
